project_id = "idufpxzvskjrwaslnsco"

[functions.create-invoice]
verify_jwt = false

[functions.create-lounge-invoice]
verify_jwt = false

[functions.generate-u18-pdf]
verify_jwt = false

[functions.send-reservation-notification]
verify_jwt = false

[functions.check-in-ticket]
verify_jwt = false

[functions.analyze-image-crop]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.create-mollie-payment]
verify_jwt = false

[functions.mollie-webhook]
verify_jwt = false

[functions.create-lounge-payment]
verify_jwt = false

[functions.sync-outbound]
verify_jwt = false